DROP TABLE IF EXISTS address;
CREATE TABLE address (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  city VARCHAR(45) NOT NULL,
  plz VARCHAR(10) NOT NULL,
  street VARCHAR(45) NOT NULL,
  housenumber VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  surname VARCHAR(45) NOT NULL,
  lastname VARCHAR(45) NOT NULL,
  age INTEGER UNSIGNED NOT NULL,
  birth DATE NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;

ALTER TABLE address ADD COLUMN userid INTEGER UNSIGNED NOT NULL AFTER housenumber;
ALTER TABLE address ADD CONSTRAINT fk_user FOREIGN KEY fk_user (userid) REFERENCES user (id) ON DELETE RESTRICT ON UPDATE RESTRICT;
